#pragma once

//
// This file contains all IDs of game assets 
//

#define ID_TEX_MARIO 0
#define ID_TEX_ENEMY 10
#define ID_TEX_ENEMY_REVERSE 11
#define ID_TEX_MISC 20


#define OBJECT_TYPE_MARIO	0
#define OBJECT_TYPE_BRICK	1
#define OBJECT_TYPE_GOOMBA	2
#define OBJECT_TYPE_KOOPA	3
#define OBJECT_TYPE_COIN 4
#define OBJECT_TYPE_PLATFORM 5
#define OBJECT_TYPE_BOX 6
#define OBJECT_TYPE_RED_KOOPA 7
#define OBJECT_TYPE_CHECK_FALL 8
#define OBJECT_TYPE_CHECK_FALL_KOOPA_ON_GLASS_BRICK 9
#define OBJECT_TYPE_RED_PARA_GOOMBA 10

#define OBJECT_TYPE_PORTAL	50


#pragma region MARIO 

#define ID_SPRITE_MARIO 10000
#define ID_SPRITE_MARIO_BIG (ID_SPRITE_MARIO + 1000)
#define ID_SPRITE_MARIO_BIG_IDLE (ID_SPRITE_MARIO_BIG + 100)
#define ID_SPRITE_MARIO_BIG_IDLE_LEFT (ID_SPRITE_MARIO_BIG_IDLE + 10) //11110
#define ID_SPRITE_MARIO_BIG_IDLE_RIGHT (ID_SPRITE_MARIO_BIG_IDLE + 20) //11120

#define ID_SPRITE_MARIO_BIG_WALKING (ID_SPRITE_MARIO_BIG + 200) //11200
#define ID_SPRITE_MARIO_BIG_WALKING_LEFT (ID_SPRITE_MARIO_BIG_WALKING + 10)	//11210
#define ID_SPRITE_MARIO_BIG_WALKING_RIGHT (ID_SPRITE_MARIO_BIG_WALKING + 20)	//11220
#define ID_SPRITE_MARIO_BIG_RUNNING (ID_SPRITE_MARIO_BIG + 300)	//11300	
#define ID_SPRITE_MARIO_BIG_RUNNING_LEFT (ID_SPRITE_MARIO_BIG_RUNNING + 10)	//11310
#define ID_SPRITE_MARIO_BIG_RUNNING_RIGHT (ID_SPRITE_MARIO_BIG_RUNNING + 20)	//11320
#define ID_SPRITE_MARIO_BIG_JUMP (ID_SPRITE_MARIO_BIG + 400)	//11400
#define ID_SPRITE_MARIO_BIG_JUMP_WALK (ID_SPRITE_MARIO_BIG_JUMP + 10)	//11410
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_LEFT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 2)	//11412
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 6)	//11416
#define ID_SPRITE_MARIO_BIG_JUMP_RUN (ID_SPRITE_MARIO_BIG_JUMP + 20)	//11420
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_LEFT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 2)	//11422
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 6)	//11426
#define ID_SPRITE_MARIO_BIG_SIT (ID_SPRITE_MARIO_BIG + 500)	//11500
#define ID_SPRITE_MARIO_BIG_SIT_LEFT (ID_SPRITE_MARIO_BIG_SIT + 10)	//11510
#define ID_SPRITE_MARIO_BIG_SIT_RIGHT (ID_SPRITE_MARIO_BIG_SIT + 20)	//11520
#define ID_SPRITE_MARIO_BIG_BRACE (ID_SPRITE_MARIO_BIG + 600)	//11600
#define ID_SPRITE_MARIO_BIG_BRACE_LEFT (ID_SPRITE_MARIO_BIG_BRACE + 10)	//11610
#define ID_SPRITE_MARIO_BIG_BRACE_RIGHT (ID_SPRITE_MARIO_BIG_BRACE + 20)	//11620
#define ID_SPRITE_MARIO_BIG_KICKING	(ID_SPRITE_MARIO_BIG + 700)	//11700
#define ID_SPRITE_MARIO_BIG_KICKING_LEFT (ID_SPRITE_MARIO_BIG_KICKING + 10)	//11710
#define ID_SPRITE_MARIO_BIG_KICKING_RIGHT (ID_SPRITE_MARIO_BIG_KICKING + 20)	//11720
#define ID_SPRITE_MARIO_BIG_HOLDING (ID_SPRITE_MARIO_BIG + 800)	//11800
#define ID_SPRITE_MARIO_BIG_HOLDING_IDLE_LEFT (ID_SPRITE_MARIO_BIG_HOLDING + 10)	//11810
#define ID_SPRITE_MARIO_BIG_HOLDING_IDLE_RIGHT (ID_SPRITE_MARIO_BIG_HOLDING + 20)	//11820
#define ID_SPRITE_MARIO_BIG_HOLDING_WALK_LEFT (ID_SPRITE_MARIO_BIG_HOLDING + 30)	//11830
#define ID_SPRITE_MARIO_BIG_HOLDING_WALK_RIGHT (ID_SPRITE_MARIO_BIG_HOLDING + 40)	//11840

#define ID_SPRITE_MARIO_DIE (ID_SPRITE_MARIO + 3000)	//11300

#define ID_SPRITE_MARIO_SMALL (ID_SPRITE_MARIO + 2000)	//12000
#define ID_SPRITE_MARIO_SMALL_IDLE (ID_SPRITE_MARIO_SMALL + 100)	//12100
#define ID_SPRITE_MARIO_SMALL_IDLE_LEFT (ID_SPRITE_MARIO_SMALL_IDLE + 10)	//12110
#define ID_SPRITE_MARIO_SMALL_IDLE_RIGHT (ID_SPRITE_MARIO_SMALL_IDLE + 20)	//12120

#define ID_SPRITE_MARIO_SMALL_WALKING (ID_SPRITE_MARIO_SMALL + 200)	//12200
#define ID_SPRITE_MARIO_SMALL_WALKING_LEFT (ID_SPRITE_MARIO_SMALL_WALKING + 10)	//12210
#define ID_SPRITE_MARIO_SMALL_WALKING_RIGHT (ID_SPRITE_MARIO_SMALL_WALKING + 20)	//12220
#define ID_SPRITE_MARIO_SMALL_RUNNING (ID_SPRITE_MARIO_SMALL + 300)	//12300
#define ID_SPRITE_MARIO_SMALL_RUNNING_LEFT (ID_SPRITE_MARIO_SMALL_RUNNING + 10)
#define ID_SPRITE_MARIO_SMALL_RUNNING_RIGHT (ID_SPRITE_MARIO_SMALL_RUNNING + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP (ID_SPRITE_MARIO_SMALL + 400)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK (ID_SPRITE_MARIO_SMALL_JUMP + 10)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN (ID_SPRITE_MARIO_SMALL_JUMP + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 6)

#define ID_SPRITE_MARIO_SMALL_SIT (ID_SPRITE_MARIO_SMALL + 500)
#define ID_SPRITE_MARIO_SMALL_SIT_LEFT (ID_SPRITE_MARIO_SMALL_SIT + 10)
#define ID_SPRITE_MARIO_SMALL_SIT_RIGHT (ID_SPRITE_MARIO_SMALL_SIT + 20)

#define ID_SPRITE_MARIO_SMALL_BRACE (ID_SPRITE_MARIO_SMALL + 500)
#define ID_SPRITE_MARIO_SMALL_BRACE_LEFT (ID_SPRITE_MARIO_SMALL_BRACE + 10)
#define ID_SPRITE_MARIO_SMALL_BRACE_RIGHT (ID_SPRITE_MARIO_SMALL_BRACE + 20)

#pragma endregion 

#define ID_SPRITE_BRICK 20000

#define ID_SPRITE_GOOMBA 30000
#define ID_SPRITE_GOOMBA_WALK (ID_SPRITE_GOOMBA + 1000)
#define ID_SPRITE_GOOMBA_DIE (ID_SPRITE_GOOMBA + 2000)

#define ID_SPRITE_RED_PARA_GOOMBA	33000
#define ID_SPRITE_RED_WINGED_PARA_GOOMBA_WALKING 33100
#define ID_SPRITE_RED_WINGED_PARA_GOOMBA_JUMPING 33200
#define ID_SPRITE_RED_WINGED_PARA_GOOMBA_HOPPING 33300
#define ID_SPRITE_RED_PARA_GOOMBA_WALKING 33400
#define ID_SPRITE_RED_PARA_GOOMBA_DIE 33500


#define ID_SPRITE_KOOPA 35000
#define ID_SPRITE_KOOPA_WALK_LEFT (ID_SPRITE_KOOPA + 100)
#define ID_SPRITE_KOOPA_WALK_RIGHT (ID_SPRITE_KOOPA + 110)
#define ID_SPRITE_KOOPA_SHELL (ID_SPRITE_KOOPA + 200)
#define ID_SPRITE_KOOPA_DIE (ID_SPRITE_KOOPA + 300)

#define ID_SPRITE_RED_KOOPA 36000
#define ID_SPRITE_RED_KOOPA_WALK_LEFT (ID_SPRITE_RED_KOOPA + 100)
#define ID_SPRITE_RED_KOOPA_WALK_RIGHT (ID_SPRITE_RED_KOOPA + 110)
#define ID_SPRITE_RED_KOOPA_SHELL (ID_SPRITE_RED_KOOPA + 200)
#define ID_SPRITE_RED_KOOPA_DIE (ID_SPRITE_RED_KOOPA + 300)

#define ID_SPRITE_COIN 40000

#define ID_SPRITE_CLOUD 50000
#define ID_SPRITE_CLOUD_BEGIN (ID_SPRITE_CLOUD+1000)
#define ID_SPRITE_CLOUD_MIDDLE (ID_SPRITE_CLOUD+2000)
#define ID_SPRITE_CLOUD_END (ID_SPRITE_CLOUD+3000)